### ISSUE TITLE
Bug: Files are always downloaded with the strange filename "86400"

### ISSUE THREAD

**Issue by bytesparrow** [andrewhancox/moodle-customfield_file#5]
Instead of e.g. showing an image in the browser, a file called "86400" is downloaded.

send_file is used incorrectly, I would commit the fix if that's ok

**Comment by andrewhancox** [comment]
This was intentional. I built this plugin to handle files that would be downloaded. There’s another field I’ve built for showing images.

**Comment by bytesparrow** [comment]
The problem is, that `send_file` is used incorrectly. 
The code says
`send_file($file, 86400, 0, $forcedownload, $options);`
but send_file is implemented like that:
`send_file($path, $filename, $lifetime = null , $filter=0, $pathisstring=false, $forcedownload=false, $mimetype='',
                   $dontdie=false, array $options = array())`
so send_file expects "$filename" as second parameter. 
In this case $filename is 86400. 
This means that at the moment all the other variables in the code get mixed up as well.

**Comment by andrewhancox** [comment]
This was already fixed on main_39 - which is the active branch, I've updated the repo settings so it is now the default branch.
